site_name: Pytdx
site_description: Python tdx数据接口

theme: readthedocs

pages:
  - 文档概述: 'index.md'
  - 快速安装: 'installation.md'

  - '行情接口':
    - '标准行情': 'pytdx_hq.md'
    - '扩展行情': 'pytdx_exhq.md'
    - '数据读取': 'pytdx_reader.md'
    - '财务数据': 'pytdx_crawler.md'
    - '交易相关': 'pytdx_trade.md'
    - '连 接 池': 'pytdx_pool.md'
  - '命令行工具':
    - '行情工具': 'hqget.md'
    - '数据工具': 'hqreader.md'

  - 常见问题和解决方案整理FAQ:
    - '同花顺的一个爬虫 可以获取前后复权因子': 'fuquan_factor.md'
    - '数据的批量完整下载方式代码': 'batch_download_data.md'
    - '基金价格问题': 'hq_price.md'


